### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by M1SM4TCH** [LeCodeCo/AntiBotDeluxeEX#10]
## License
**Spigot Profile URL:**  
https://www.spigotmc.org/members/zaniquelli.281154/

**Discord:**  
M1SM4TCH#0514

## Server Information
**Platform:**
- [X] Spigot
- [] BungeeCord

**Fork:**
- [] None
- [X] PaperSpigot
- [ ] Waterfall
- [ ] HexaCord
- [ ] Travertine

**Panel:**
- [X] Yes, Multicraft
- [ ] Yes, PufferPanel
- [ ] Yes, Pterodactyl
- [ ] Yes
- [] No

**Plus:** 
- [ ] Yes
- [X] No

**Host:**  
- [X] Minecraft
- [ ] Dedicated, Linux
- [ ] Dedicated, Win
- [ ] VPS, Linux
- [ ] VPS, Win

**Java Version:**  (I have no idea, probabally 8)
- [ ] Java 9
- [ ] Java 8
- [ ] Java 7

## Issue
**Describe issue:**  
The plugin doesn't starts 💃 

**Config:**  
https://file.properties/paste/oboqumixok.bash

**AntiBotDeluxe Log:**  
https://file.properties/paste/iwaratepud.makefile

**Errors**  
https://file.properties/paste/wojayocatu.md

**Comment by FusionCoding** [comment]
Multicraft misloaded the ClassLoader, this issue is related to your host with Multicraft.

**Comment by M1SM4TCH** [comment]
What i need to do? e.e

**Comment by FusionCoding** [comment]
Talk about that on our Discord.
