### ISSUE TITLE
Errors in console | last version AntiBotDeluxeEX

### ISSUE THREAD

**Issue by JavituRec** [LeCodeCo/AntiBotDeluxeEX#11]
### Information
Error in console with last version plugin.

## License
**Spigot Profile URL:**  
https://www.spigotmc.org/members/javiturec.25015/

**Discord:**  
jX2018#9374

## Server Information
**Platform:**
- [ ] Spigot
- [X] BungeeCord

**Fork:**
- [X] None
- [ ] Waterfall
- [ ] HexaCord
- [ ] Travertine

**Panel:**
- [ ] Yes, Multicraft
- [ ] Yes, PufferPanel
- [ ] Yes, Pterodactyl
- [ ] Yes
- [X] No

**Plus:** 
- [ ] Yes
- [X] No

**Host:**  
- [X] Dedicated, Linux (centos 7)
- [ ] Dedicated, Win
- [ ] VPS, Linux
- [ ] VPS, Win
- [ ] Minecraft

**Java Versipn:**  
- [ ] Java 9
- [X] Java 8
- [ ] Java 7

## Issue
**Describe issue:**  
I get a errors in console with last version of antibotdeluxe.

**Config:**  
https://hastebin.com/ohesabecen.bash

**AntiBotDeluxe Log:**  
https://hastebin.com/firesukuvu.vbs

**Errors**  
https://hastebin.com/afitafihey.rb
https://hastebin.com/kadikoduqa.rb
https://hastebin.com/gahoxivihe.rb

**Comment by FusionCoding** [comment]
Fixed
