### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ectalure** [LeCodeCo/AntiBotDeluxeEX#12]
# AntiBotDeluxe Issue Tracker
Error

#License
https://www.spigotmc.org/members/ectalure.299552/

**Discord:**  
Ectalure#3139

## Server Information
- [X] Paperspigot

**Fork:**
- [X] None

**Panel:**
- [X] No

**Plus:** 
- [X] No

**Host:**  
- [X] Dedicated, Linux OVH

**Java Versipn:**  
- [X] Java 8

## Issue
**Describe issue:**  
With the last version, the server start with the error in the console and come frequently with just the Task #Number change and when a player join the server, the error n°2 appear.

**Config:**  
https://hastebin.com/qopucuseco.pl

**AntiBotDeluxe Log:**  
https://hastebin.com/ewilosokav.hs

**Error 1**  
https://hastebin.com/kapugijota.vbs

**Error 2**  
https://hastebin.com/mevuhuneju.vbs
(Not here when the plugin is not enable)

**List of all plugins**

worldguard-6.2.jar
worldedit-bukkit-6.1.7.3.jar
WorldBorder.jar
ViaVersion-1.3.0.jar
Vault.jar
TAB_v1.6.4.jar
Staff+.jar
SkinsRestorer-v12.9.4.jar
React-5.7.jar
safetrade-1.0.15.jar
RandomCoordinatesV2.jar
ProtocolLib.jar
PlaceholderAPI-2.8.2.jar
PandaWire-1.8.8.jar
NoSpawnerChange.jar
MyCommand.jar
Multiverse-Core-2.6.0-SNAPSHOT.jar
mineweb_bridge-2.0.0-no-injector.jar
MassiveCore.jar
LuckPerms-Bukkit-4.0.80.jar
KothScoreboard.jar
KOTH.jar
ItemRestrict-2.4.1.jar
ItemCases.jar
HolographicDisplays.jar
FastLogin.jar
FastAsyncWorldEdit-bukkit-17.12.15-0dbb617-949-18.0.6.jar
Factions.jar
FactionChat.jar
EssentialsXSpawn-2.0.1.jar
EssentialsXProtect-2.0.1.jar
EssentialsXGeoIP-2.0.1.jar
EssentialsXChat-2.0.1.jar
EssentialsX-2.0.1.jar
EpicSpawners 3.1.6 R11.jar
EnderPearlCooldown-1.5.0.jar
EasyBackup.jar
DeluxeMenus-1.10.2.jar
DeathMessagesPrime.jar
CustomPayloadFixer.jar
CreativeGates.jar
ConditionalCommands-1.4-SNAPSHOT.jar
CombatLogX.jar
ColoredAnvils.jar
ClearAll.jar
ChocoRankup 1.1.0 (Build 10).jar           (Our plugin)
ChocoPCCooldown 1.0.2 (Build 4).jar    (Our plugin)
ChocoDropEgg.jar                                 (Our plugin)
ChatControl.jar
BottledExp2.2.3.2.jar
boosCooldowns.jar
BlowableObsidians.jar
AuthMe-5.5.0-SNAPSHOT.jar
AuctionHouse.jar
Arconix.jar
AntiBotDeluxeEX.jar
AdvancedBan-2.1.4-RELEASE.jar
AAC.jar

**Comment by FusionCoding** [comment]
Fixed
