### ISSUE TITLE
Error on bungee console spammed

### ISSUE THREAD

**Issue by xion87** [LeCodeCo/AntiBotDeluxeEX#13]
# AntiBotDeluxe Issue Tracker
The revolution of Anti Bot systems.

### Information
Welcome to the AntiBotDeluxe Issue Tracker.  
Please fill in required information accurately or support will not be provided.  

__Ensure you are on the latest version before submitting an issue!__

## License
**Spigot Profile URL:**  
https://www.spigotmc.org/members/malachiel.7161/

**Discord:**  
Malachiel#8561

## Server Information
**Platform:**
- [ ] Spigot
- [X] BungeeCord

**Fork:**
- [ ] None
- [X] Waterfall
- [ ] HexaCord
- [ ] Travertine

**Panel:**
- [ ] Yes, Multicraft
- [ ] Yes, PufferPanel
- [X] Yes, Pterodactyl
- [ ] Yes
- [ ] No

**Plus:** 
- [ ] Yes
- [X] No

**Host:**  
- [X] Dedicated, Linux
- [ ] Dedicated, Win
- [ ] VPS, Linux
- [ ] VPS, Win
- [ ] Minecraft

**Java Versipn:**  
- [ ] Java 9
- [X] Java 8
- [ ] Java 7

## Issue
**Describe issue:**  
I see errors on bungeecord spammed on bungee console

**Config:**  
https://hastebin.com/epebeqakag.pl

**AntiBotDeluxe Log:**  
https://hastebin.com/jasarikube.http

**Errors**  
https://hastebin.com/iwifazehat.md

**Comment by FusionCoding** [comment]
Fixed
