### ISSUE TITLE
More Errors on bungee console

### ISSUE THREAD

**Issue by xion87** [LeCodeCo/AntiBotDeluxeEX#16]
# AntiBotDeluxe Issue Tracker
The revolution of Anti Bot systems.

### Information
Welcome to the AntiBotDeluxe Issue Tracker.  
Please fill in required information accurately or support will not be provided.  

__Ensure you are on the latest version before submitting an issue!__

## License
**Spigot Profile URL:**  
https://www.spigotmc.org/members/malachiel.7161/

**Discord:**  
Malachiel#8561

## Server Information
**Platform:**
- [ ] Spigot
- [X] BungeeCord

**Fork:**
- [ ] None
- [X] Waterfall
- [ ] HexaCord
- [ ] Travertine

**Panel:**
- [ ] Yes, Multicraft
- [ ] Yes, PufferPanel
- [X] Yes, Pterodactyl
- [ ] Yes
- [ ] No

**Plus:** 
- [ ] Yes
- [X] No

**Host:**  
- [X] Dedicated, Linux
- [ ] Dedicated, Win
- [ ] VPS, Linux
- [ ] VPS, Win
- [ ] Minecraft

**Java Versipn:**  
- [ ] Java 9
- [X] Java 8
- [ ] Java 7

Config:
https://hastebin.com/wagibejipa.bash

AntiBotDeluxe Log:
https://hastebin.com/gahuzicoge.scala

Errors
https://hastebin.com/juxarudiwi.md

**Comment by FusionCoding** [comment]
Already fixed with latest release.

**Comment by xion87** [comment]
I messed the error logs with old ones sorry, the correct logs and config are these ones:
Config:
https://hastebin.com/wagibejipa.bash

AntiBotDeluxe Log:
https://hastebin.com/gahuzicoge.scala

Errors
https://hastebin.com/juxarudiwi.md

**Comment by FusionCoding** [comment]
We now tried to replicate this error over some time, could you please describe when and what causes this?

**Comment by xion87** [comment]
I don't know i see it a lot of times here, Here there is the full bungee log
[latest.zip](https://github.com/LeCodeCo/AntiBotDeluxeEX/files/1628543/latest.zip)

**Comment by FusionCoding** [comment]
Please try 9.1.3a
