### ISSUE TITLE
Error: java.lang.IllegalArgumentException: Name cannot be null

### ISSUE THREAD

**Issue by lucas2107** [LeCodeCo/AntiBotDeluxeEX#18]
## License
**Spigot Profile URL:**  
https://www.spigotmc.org/members/lucas2107.169001/

**Discord:**  
Lucas2107#3788

## Server Information
**Platform:**
- [X] Spigot
- [ ] BungeeCord

**Fork:**
- [X] None
- [ ] Waterfall
- [ ] HexaCord
- [ ] Travertine

**Panel:**
- [ ] Yes, Multicraft
- [ ] Yes, PufferPanel
- [ ] Yes, Pterodactyl
- [ ] Yes
- [X] No

**Plus:** 
- [X] Yes
- [ ] No

**Host:**  
- [X] Dedicated, Linux
- [ ] Dedicated, Win
- [ ] VPS, Linux
- [ ] VPS, Win
- [ ] Minecraft

**Java Versipn:**  
- [ ] Java 9
- [X] Java 8
- [ ] Java 7

## Issue
**Describe issue:**  
This error is happenning sometimes, randomly.

**Config:**  
https://file.properties/paste/odajicaqoz

**AntiBotDeluxe Log:**  
https://file.properties/paste/ogerazogob

**Errors**  
https://file.properties/paste/fuxilibubi.md

**Comment by FusionCoding** [comment]
That should not happen,

marked & remembered for 9.3
