### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SebaGaming** [LeCodeCo/AntiBotDeluxeEX#2]
05.01 23:18:16 [Server] ERROR Exception in thread "pool-9334-thread-1" java.lang.NullPointerException
05.01 23:18:16 [Server] ERROR at de.deluxedevs.antibotdeluxeex.a.e.a(e.java:26)
05.01 23:18:16 [Server] ERROR at de.deluxedevs.antibotdeluxeex.bungee.checks.GeoCheck.doCheck(GeoCheck.java:49)
05.01 23:18:16 [Server] ERROR at de.deluxedevs.antibotdeluxeex.bungee.checks.GeoCheck.doCheck(GeoCheck.java:16)
05.01 23:18:16 [Server] ERROR at de.deluxedevs.antibotdeluxeex.bungee.e.b.lambda$onPreLogin$0(b.java:77)
05.01 23:18:16 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
05.01 23:18:16 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
05.01 23:18:16 [Server] ERROR at java.lang.Thread.run(Thread.java:748)

Getting This error in BungeCord console!

**Comment by LeCodeCo** [comment]
We are unable to find the source of this error as the whole template was removed and we are unable to check required system information.
