### ISSUE TITLE
When a player joins the server, the server will display an error

### ISSUE THREAD

**Issue by disqetow** [LeCodeCo/AntiBotDeluxeEX#5]
# AntiBotDeluxe Issue Tracker
The revolution of Anti Bot systems.

### Information
Welcome to the AntiBotDeluxe Issue Tracker.  
Please fill in required information accurately or support will not be provided.  

__Ensure you are on the latest version before submitting an issue!__

## License
**Spigot Profile URL:**  
https://www.spigotmc.org/members/example.0/

**Discord:**  
disqeto#0763

## Server Information
**Platform:**
- [x] Spigot
- [ ] BungeeCord

**Fork:**
- [X] None
- [ ] Waterfall
- [ ] HexaCord
- [ ] Travertine

**Panel:**
- [X] Yes, Multicraft
- [ ] Yes, PufferPanel
- [ ] Yes, Pterodactyl
- [ ] Yes
- [ ] No

**Plus:** 
- [ ] Yes
- [X] No

**Host:**  
- [X] Dedicated, Linux
- [ ] Dedicated, Win
- [ ] VPS, Linux
- [ ] VPS, Win
- [ ] Minecraft

**Java Versipn:**  
- [ ] Java 9
- [X] Java 8
- [X] Java 7

## Issue
**Describe issue:**  
When a player joins the server, the server will display an error

**Config:**  
https://pastebin.com/fqAdMadn

**AntiBotDeluxe Log:**  
https://pastebin.com/UeXjWbNG

**Errors**  
https://pastebin.com/2D2zr949

**Comment by FusionCoding** [comment]
You try to use DeluxeAI without having MaxConnectionsPerIP-hold enabled.

**Comment by disqetow** [comment]
Still have this error.
