### ISSUE TITLE
Massive kicks | Proxies | Redis

### ISSUE THREAD

**Issue by JavituRec** [LeCodeCo/AntiBotDeluxeEX#6]
**Information**

I have two dedicated servers and I have two proxies in same dedicated server with redis and antibotdeluxe is installed in my two proxies. 

**Spigot Profile URL:**  
https://www.spigotmc.org/members/javiturec.25015/

**Discord:**  
jX2018#9374

**Platform:**
- [ ] Spigot
- [X] BungeeCord

**Fork:**
- [X] None
- [ ] Waterfall
- [ ] HexaCord
- [ ] Travertine

**Panel:**
- [ ] Yes, Multicraft
- [ ] Yes, PufferPanel
- [ ] Yes, Pterodactyl
- [ ] Yes
- [X] No

**Plus:** 
- [ ] Yes
- [X] No

**Host:**  
- [X] Dedicated, Linux (centos 7)
- [ ] Dedicated, Win
- [ ] VPS, Linux
- [ ] VPS, Win
- [ ] Minecraft

**Java Versipn:**  
- [ ] Java 9
- [X] Java 8
- [ ] Java 7

**Describe issue:**  

Massively today 100 users were kicked to the hub several times. I have found two similar errors.

**Config:**  
https://hastebin.com/ibibajiqut.bash

**AntiBotDeluxe Log:**  
https://hastebin.com/hazasovewu.css

**Errors**  
1.- https://hastebin.com/dihokevebi.rb
2.- https://hastebin.com/akobiqibat.rb

**Comment by FusionCoding** [comment]
Will be fixed with next update. Anyways the Error should not kick anyone.
