### ISSUE TITLE
[ERROR] Spamming console

### ISSUE THREAD

**Issue by lolo773** [LeCodeCo/AntiBotDeluxeEX#7]
# AntiBotDeluxe Issue Tracker
The revolution of Anti Bot systems.

### Information
Welcome to the AntiBotDeluxe Issue Tracker.  
Please fill in required information accurately or support will not be provided.  

__Ensure you are on the latest version before submitting an issue!__

## License
**Spigot Profile URL:**  
https://www.spigotmc.org/members/hksurvivalowner.251277/

**Discord:**  
HKNoob#3226

## Server Information
**Platform:**
- [X] Spigot
- [ ] BungeeCord

**Fork:**
- [X] None
- [ ] Waterfall
- [ ] HexaCord
- [ ] Travertine

**Panel:**
- [X] Yes, Multicraft
- [ ] Yes, PufferPanel
- [ ] Yes, Pterodactyl
- [ ] Yes
- [] No

**Plus:** 
- [ ] Yes
- [X] No

**Host:**  
- [ ] Dedicated, Linux
- [ ] Dedicated, Win
- [ ] VPS, Linux
- [ ] VPS, Win
- [X] Minecraft

**Java Versipn:**  
- [ ] Java 9
- [X] Java 8
- [ ] Java 7

## Issue
**Describe issue:**  
Describe your issue and exactly how to replicate it here in as much detail as possible.
The plugin is keep spamming my console with following error messages.
**Config:**  
https://hastebin.com/faxavarili.pl

**AntiBotDeluxe Log:**  
https://hastebin.com/oqocahajiz.hs

**Errors**  
https://hastebin.com/kawosirotu.vbs

**Comment by FusionCoding** [comment]
That is caused by your hosting.
