### ISSUE TITLE
Error in console..

### ISSUE THREAD

**Issue by AleMastro** [LeCodeCo/AntiBotDeluxeEX#8]
# AntiBotDeluxe Issue Tracker
The revolution of Anti Bot systems.

### Information
Welcome to the AntiBotDeluxe Issue Tracker.  
Please fill in required information accurately or support will not be provided.  

__Ensure you are on the latest version before submitting an issue!__

## License
**Spigot Profile URL:**  
https://www.spigotmc.org/members/_alemastro_.34285/

**Discord:**  
AleMastro#6899

## Server Information
**Platform:**
- [ ] Spigot
- [X] BungeeCord

**Fork:**
- [ ] None
- [X] Waterfall
- [ ] HexaCord
- [ ] Travertine

**Panel:**
- [ ] Yes, Multicraft
- [ ] Yes, PufferPanel
- [ ] Yes, Pterodactyl
- [ ] Yes
- [X] No

**Plus:** 
- [X] Yes
- [ ] No

**Host:**  
- [ ] Dedicated, Linux
- [ ] Dedicated, Win
- [ ] VPS, Linux
- [ ] VPS, Win
- [X] Minecraft

**Java Versipn:**  
- [ ] Java 9
- [X] Java 8
- [ ] Java 7

## Issue
**Describe issue:**  
Error in console..

**Config:**  
https://hastebin.com/manekeraju.bash

**AntiBotDeluxe Log:**  
https://hastebin.com/

**Errors**  
https://hastebin.com/utedezakub.rb or NA

**Comment by FusionCoding** [comment]
Fixed
